version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - npm install -g gulp
      - npm install -i
  build:
    commands:
      - gulp build
artifacts:
  files:
    - '**/*'
  base-directory: dist